# Generated by Django 3.1.8 on 2021-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Option_A', models.TextField()),
                ('Option_B', models.TextField()),
                ('Option_C', models.TextField()),
                ('Option_D', models.TextField()),
                ('Correct_Answer', models.TextField()),
                ('Tag', models.TextField()),
            ],
        ),
    ]
