# Generated by Django 3.1.8 on 2021-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_last', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('stream', models.CharField(max_length=20)),
                ('graduation_year', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
