# Generated by Django 3.1.8 on 2021-06-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userportal', '0006_auto_20210603_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_id',
        ),
    ]
